#ifndef SPINCHAINS_GLOBALVARIABLES_H
#define SPINCHAINS_GLOBALVARIABLES_H

#include <Eigen/Eigenvalues> // header for Eigen
#include <string>

class GlobalVariablesClass{
private:

    int                 _numSpins; // Number of sites (spins) in the chain
    //Mac std::string         _filePath = "/Users/cameronmceleney/CLionProjects/Data/"; // Path to directory where all files will be saved
    std::string         _filePath = "D:/Data/RK2 Tests/";
    std::string         _fileNameBase; // Forms the first part of any filename generated by one iteration of this software
    double              _exchangeMinVal; // minimum exchange value (J_min)
    double              _exchangeMaxVal; // maximum exchange value (J_min)

public:

    int                 GetNumSpins();
    void                SetNumSpins(int numSpins);

    std::string         GetFilePath();
    void                SetFilePath(std::string filePath);

    std::string         GetFileNameBase();
    void                SetFileNameBase(std::string fileNameBase);

    double              GetExchangeMinVal(); // minimum exchange value (T)
    void                SetExchangeMinVal(double exchangeMinimum);

    double              GetExchangeMaxVal(); // maximum exchange value (T)
    void                SetExchangeMaxVal(double exchangeMaximum);

};


#endif //SPINCHAINS_GLOBALVARIABLES_H
