#ifndef SPINCHAINS_GLOBALVARIABLES_H
#define SPINCHAINS_GLOBALVARIABLES_H

#include <Eigen/Eigenvalues> // header for Eigen
#include <iomanip>
#include <string>

class GlobalVariablesClass{

private:
//  Dtype               Member Name                             //Comment
    double              _staticBiasField;                       // Applied bias field [T]. Often written as H_0 or H_static in literature
    int                 _numSpins;                              // Number of sites (spins) in the chain
    std::string         _filePath;                              // Path to directory where all files will be saved
    std::string         _fileNameBase;                          // Forms the first part of any filename generated by one iteration of this software
    double              _exchangeMinVal;                        // minimum exchange value (J_min)
    double              _exchangeMaxVal;                        // maximum exchange value (J_min)
    std::string         dateToday;                             // Contains today's date.
    std::string         _currentTime;

    // Private Functions
    std::string         FindDateToday();                        // Finds today's date in the standard format for this code

public:
//  Dtype               Member Name                             //Comment
    int                 GetNumSpins();
    void                SetNumSpins(int numSpins);

    std::string         GetFilePath();
    void                SetFilePath();

    std::string         GetFileNameBase();
    void                SetFileNameBase(std::string fileNameBase);

    double              GetExchangeMinVal();
    void                SetExchangeMinVal(double exchangeMinimum);

    double              GetExchangeMaxVal();
    void                SetExchangeMaxVal(double exchangeMaximum);

    double              GetStaticBiasField();
    void                SetStaticBiasField(double staticBiasField);

    std::string         GetCurrentTime();
    void                SetCurrentTime();

};


#endif //SPINCHAINS_GLOBALVARIABLES_H
